CREATE USER infi IDENTIFIED BY infi;

GRANT ALL PRIVILEGES TO infi;

CREATE TABLE "INFI"."T_INF_MENU" 
   (	"RCP_KY" NUMBER NOT NULL ENABLE, 
	"RCP_NM" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"RCP_TYP" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER, 
	"ACTV_FL" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"CRT_TS" TIMESTAMP (6) DEFAULT systimestamp, 
	"UPD_TS" TIMESTAMP (6), 
	 CONSTRAINT "UNIQ_RCP_NM" UNIQUE ("RCP_NM"));
	 
CREATE TABLE "INFI"."T_INF_RCP_DTL"
   (	"RCP_NM" VARCHAR2(100 BYTE), 
	"ING_NM" VARCHAR2(100 BYTE), 
	"ING_MSR" VARCHAR2(100 BYTE), 
	"ING_QTY" NUMBER(10,0), 
	"CRT_TS" TIMESTAMP (6) DEFAULT systimestamp, 
	"UPD_TS" TIMESTAMP (6), 
	"RCP_KY" NUMBER
   );
   
CREATE TABLE "INFI"."T_EXEC_LOG" 
   (	"TABLE_NM" VARCHAR2(20 BYTE), 
	"MESSAGE" VARCHAR2(200 BYTE), 
	"ELASPSED_TIME" NUMBER, 
	"START_TIME" TIMESTAMP (6), 
	"END_TIME" TIMESTAMP (6)
   );
   
CREATE SEQUENCE  "INFI"."SEQ_RCP_DTL"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;   
  