INSERT INTO INFI.T_INF_RCP_DTL (RCP_KY,RCP_NM,ING_NM,ING_MSR,ING_QTY) VALUES(SEQ_RCP_DTL.NEXTVAL,'Tea', 'Water', 'Cup', '1');
INSERT INTO INFI.T_INF_RCP_DTL (RCP_KY,RCP_NM,ING_NM,ING_MSR,ING_QTY) VALUES(SEQ_RCP_DTL.NEXTVAL,'Tea', 'Milk', 'Cup', '1');
INSERT INTO INFI.T_INF_RCP_DTL (RCP_KY,RCP_NM,ING_NM,ING_MSR,ING_QTY) VALUES(SEQ_RCP_DTL.NEXTVAL,'Tea', 'Tea Leaves', 'Teaspoon', '1');
INSERT INTO INFI.T_INF_RCP_DTL (RCP_KY,RCP_NM,ING_NM,ING_MSR,ING_QTY) VALUES(SEQ_RCP_DTL.NEXTVAL,'Tea', 'Sugar', 'Tablespoon', '1');
INSERT INTO INFI.T_INF_RCP_DTL (RCP_KY,RCP_NM,ING_NM,ING_MSR,ING_QTY) VALUES(SEQ_RCP_DTL.NEXTVAL,'Fries', 'Potato', 'Pound', '1');
INSERT INTO INFI.T_INF_RCP_DTL (RCP_KY,RCP_NM,ING_NM,ING_MSR,ING_QTY) VALUES(SEQ_RCP_DTL.NEXTVAL,'Fries', 'Oil', 'Cup', '1');
INSERT INTO INFI.T_INF_RCP_DTL (RCP_KY,RCP_NM,ING_NM,ING_MSR,ING_QTY) VALUES(SEQ_RCP_DTL.NEXTVAL,'Fries', 'Salt', 'Tablespoon', '2');
INSERT INTO INFI.T_INF_RCP_DTL (RCP_KY,RCP_NM,ING_NM,ING_MSR,ING_QTY) VALUES(SEQ_RCP_DTL.NEXTVAL,'Paneer Curry', 'Paneer', 'Pound', '1');
INSERT INTO INFI.T_INF_RCP_DTL (RCP_KY,RCP_NM,ING_NM,ING_MSR,ING_QTY) VALUES(SEQ_RCP_DTL.NEXTVAL,'Paneer Curry', 'Onion', 'Pound', '1');
INSERT INTO INFI.T_INF_RCP_DTL (RCP_KY,RCP_NM,ING_NM,ING_MSR,ING_QTY) VALUES(SEQ_RCP_DTL.NEXTVAL,'Choco Lava Cake', 'Milk', 'Cup', '2');
INSERT INTO INFI.T_INF_RCP_DTL (RCP_KY,RCP_NM,ING_NM,ING_MSR,ING_QTY) VALUES(SEQ_RCP_DTL.NEXTVAL,'Veg Biryani', 'Rice', 'Pound', '2');
INSERT INTO INFI.T_INF_RCP_DTL (RCP_KY,RCP_NM,ING_NM,ING_MSR,ING_QTY) VALUES(SEQ_RCP_DTL.NEXTVAL,'Veg Biryani', 'Spices', 'Teaspoon', '2');
INSERT INTO INFI.T_INF_RCP_DTL (RCP_KY,RCP_NM,ING_NM,ING_MSR,ING_QTY) VALUES(SEQ_RCP_DTL.NEXTVAL,'Ice Cream', 'Milk', 'Cup', '3');


INSERT INTO INFI.T_INF_MNU (RCP_KY,RCP_NM,RCP_TYP,PRICE) VALUES(SEQ_RCP_DTL.NEXTVAL,'Ice Cream', 'Dessert', '43');
INSERT INTO INFI.T_INF_MNU (RCP_KY,RCP_NM,RCP_TYP,PRICE) VALUES(SEQ_RCP_DTL.NEXTVAL,'Fries', 'Starter', '100');
INSERT INTO INFI.T_INF_MNU (RCP_KY,RCP_NM,RCP_TYP,PRICE) VALUES(SEQ_RCP_DTL.NEXTVAL,'Paneer Curry', 'Main Course', '150');
INSERT INTO INFI.T_INF_MNU (RCP_KY,RCP_NM,RCP_TYP,PRICE) VALUES(SEQ_RCP_DTL.NEXTVAL,'Tea', 'Drink', '30');